### ISSUE TITLE
Another platform support?

### ISSUE THREAD

**Issue by Nekspire** [chrismoos/ili9486-driver#2]
Hi!
I don't know is this good place for my question and sorry for that opened issue.
I would like to ask is there possibility to port this driver to support stm32f4xx-hal? 
I've found that you are using `stm32f1xx_hal::gpio::Dynamic;`, stm32f4xx-hal currently does not support this feature. 

Ofc, I can use stm32f4xx-hal repository locally and add this on my own, but is this good idea?

**Comment by chrismoos** [comment]
Hi @Nekspire , I don't have an `stm32f4` device but tried to implement `IoPin` for it without using the `Dynamic` pin mode. Check out the `stm32f4xx` branch and see if it works for you. If so, let me know and I'll merge it in.

**Comment by Nekspire** [comment]
Hello @chrismoos, I've tested your example code on nucleo board stm32f446re and it works pretty nice :) . However I had to add some pin definitions in [https://github.com/chrismoos/ili9486-driver/blob/stm32f4xx/src/io/stm32f4xx.rs](url).
Thanks for all!

**Comment by chrismoos** [comment]
@Nekspire ,

Glad it's working! Do you mind sending in a PR for your changes with those additional pin definitions?
